name: build
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
      - name: vet
        run: |
          go vet ./...
      - name: build
        run: |
          go build .